Unpegging urllib3.
PlaidCloud/plaid-rpc pull request #32
Opened 2021-04-29 19:35 UTC by DevinSchaffer

Superset requires urllib3 < 1.26.0 so I added conditional logic to handle older or newer versions.

2021-04-29 19:45 UTC, rad-pat requested changes

2021-04-29 20:32 UTC, DevinSchaffer commented on plaidcloud/rpc/connection/jsonrpc.py
> +                whitelist=['POST'],
You're right. I'll fix it.

2021-04-30 00:45 UTC, inviscid approved these changes
LGTM

2021-04-30 08:24 UTC, rad-pat approved these changes

2021-04-30 12:57 UTC, merged